### ISSUE TITLE
GaussianCircles2D can't be found

### ISSUE THREAD

**Issue by henrykey** [trickl/trickl-cluster#2]
hi, 
im gonna try your cluster and found no definition of class GaussianCircles2D. where can i find it? 
err msg at following line.
import com.trickl.dataset.GaussianCircles2D;

regard,

Henry

**Comment by trickl** [comment]
Hi,
  That class is defined in the dataset repository which is also on Github. 
Tim


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: henrykey <notifications@github.com> </div><div>Date:30/01/2016  02:42  (GMT+00:00) </div><div>To: trickl/trickl-cluster <trickl-cluster@noreply.github.com> </div><div>Cc:  </div><div>Subject: [trickl-cluster] GaussianCircles2D can't be found (#2) </div><div>
</div>hi, 
im gonna try your cluster and found no definition of class GaussianCircles2D where can i find it? 
err msg at following line
import comtrickldatasetGaussianCircles2D;

regard,

Henry

**Comment by henrykey** [comment]
thanks for your reply. did u mean the class is in another project? I did find it in this, there several tens of errors when building, mainly it's cause by:
The import com.trickl.dataset cannot be resolved
The import com.trickl.matrix cannot be resolved

**Comment by trickl** [comment]
Yes the classes are in another repository under the same username in github. 
You must first run maven install or those projects first (as they are not in maven central).
Hope that helps!


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: henrykey <notifications@github.com> </div><div>Date:31/01/2016  14:00  (GMT+00:00) </div><div>To: trickl/trickl-cluster <trickl-cluster@noreply.github.com> </div><div>Cc: Tim Gee <writetotimgee@gmail.com> </div><div>Subject: Re: [trickl-cluster] GaussianCircles2D can't be found (#2) </div><div>
</div>thanks for your reply. did u mean the class is in another project? I did find it in this, there several tens of errors when building, mainly it's cause by:
The import com.trickl.dataset cannot be resolved
The import com.trickl.matrix cannot be resolved

**Comment by henrykey** [comment]
I just import your project as a Git one from github. when it done, a regular Java project generated instead of maven style. I'm going to figure out what wrong with it. Poem.xml is there, so it should be a maven project. Thanks for replying.

**Comment by henrykey** [comment]
I got dataset and tried it. still need something i can't find. i just looked over your site and didn't find. where can I  get the matrix? thanks

The import com.trickl.matrix cannot be resolved	KernelPairwiseNearestNeighbour.java	/trickl-cluster-master/src/main/java/com/trickl/cluster	line 33	Java Problem

**Comment by trickl** [comment]
The classes in the matrix name space can be found here:
https://github.com/trickl/trickl-matrix
Tim

**Comment by henrykey** [comment]
Hi, Tim
Thank you very much. I found everything now and it works! Actually I’m going to try quite big data set with your sparse matrix. my dataset is about 20K records with 200K features. I hope your PCA is ok to handle the dataset.

Regards,

Henry

> 在 2016年2月1日，下午7:56，Tim Gee <notifications@github.com> 写道：
> 
> The classes in the matrix name space can be found here:
> https://github.com/trickl/trickl-matrix
> Tim
